name: Update Lambda

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BUCKET: the-last-show-30129329

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: list files
        run: ls

      - name: create deployment package
        run: |
          mkdir ./package && pip install -r requirements.txt -t ./package
          cd package && zip -r9 ../artifact.zip .
          cd ../functions/ && zip -g ../../artifact.zip create_obituary/create_obituary.py


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Upload to S3
        run: aws s3 cp artifact.zip s3://${{ env.BUCKET }}/artifact.zip

      - name: Updating Lambda
        uses: masoudkarimif/gh-action-lambda-update-slack@main
        with:
          s3_bucket: ${{ env.BUCKET }}
          s3_key: artifact.zip
          code_path: ./artifact.zip
          aws_region: ca-central-1
          env: PROD
          function_name: create_obituary