name: Update Lambda

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BUCKET: the-last-show-30129329

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: list files
        run: ls

      - name: create deployment package
        run: |
          mkdir ./package && pip install -r requirements.txt -t ./package
          cd package && zip -r9 ../artifact.zip .
          cd ../ && zip -g artifact.zip functions/*/*

        
        