name: Update Lambda

on: 
  push:
    paths:
      - 'functions/**'
      - 'requirements.txt'
      - '.github/workflows/update_lambda.yaml'
      - 'infra/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BUCKET: the-last-show-30129329

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: list files
        run: ls

      # rezips the code into a single file along with the dependencies
      - name: create deployment package
        run: |
          mkdir ./package && pip install -r requirements.txt -t ./package
          cd package && zip -r9 ../artifact.zip .
          cd ../functions/create-obituary && zip -g ../../artifact.zip create_obituary.py
          cd ../get-obituaries && zip -g ../../artifact.zip get_obituaries.py


      #configure credentials using github secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      #uploads the artifact to s3
      - name: Upload to S3
        run: aws s3 cp artifact.zip s3://${{ env.BUCKET }}/artifact.zip


      #updates the lambda function
      - name: Updating create-obituary lambda
        uses: masoudkarimif/gh-action-lambda-update-slack@main
        with:
          s3_bucket: ${{ env.BUCKET }}
          s3_key: artifact.zip
          code_path: ./artifact.zip
          aws_region: ca-central-1
          env: PROD
          function_name: create_obituary


      #updates the lambda function
      - name: Updating get-obituaries lambda
        uses: masoudkarimif/gh-action-lambda-update-slack@main
        with:
          s3_bucket: ${{ env.BUCKET }}
          s3_key: artifact.zip
          code_path: ./artifact.zip
          aws_region: ca-central-1
          env: PROD
          function_name: get_obituaries